trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    imageName: noamgal/osmexport:$(Build.BuildId)

- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: Container Registry
    command: login
    dockerRegistryEndpoint: Docker Credentials

- task: Docker@1
  displayName: Push an image
  inputs:
    command: push
    imageName: noamgal/osmexport:$(Build.BuildId)
    includeLatestTag: true
