trigger:
- master

pool:
  vmImage: Ubuntu-16.04

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Credentials'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Credentials'
    repository: 'noamgal/osmexport'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildNumber)
      latest

