trigger:
- master

pool:
  vmImage: Ubuntu-16.04

steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    imageName: noamgal/osmexport:$(Build.BuildId)
    includeLatestTag: true

- task: Docker@1
  displayName: Login
  enabled: false
  inputs:
    containerregistrytype: Container Registry
    command: login
    dockerRegistryEndpoint: Docker Credentials

- task: Docker@1
  displayName: Push an image
  inputs:
    containerregistrytype: Container Registry
    command: push
    dockerRegistryEndpoint: Docker Credentials
    imageName: noamgal/osmexport:$(Build.BuildNumber)
    includeLatestTag: true
