import globals from 'globals';
import js from '@eslint/js';
import prettierRecommended from 'eslint-plugin-prettier/recommended';

export default [
  js.configs.recommended,
  // Adds the `prettier` plugin and disables stylistic rules that conflict with it.
  prettierRecommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      // Fixable - errors
      'one-var': ['error', {const: 'never', let: 'never'}],
      'dot-notation': 'error',
      'no-else-return': ['error', {allowElseIf: false}],
      'capitalized-comments': 'error',
      'linebreak-style': 'off',
      'lines-between-class-members': 'error',
      'multiline-comment-style': 'error',
      'no-lonely-if': 'error',
      'operator-assignment': 'error',
      'padding-line-between-statements': 'error',
      'arrow-body-style': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-const': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'sort-imports': 'error',

      // Non-fixable - warnings
      'no-await-in-loop': 'warn',
      'array-callback-return': 'warn',
      'block-scoped-var': 'warn',
      complexity: 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'guard-for-in': 'warn',
      'no-alert': 'warn',
      'no-eq-null': 'warn',
      'no-implicit-globals': 'warn',
      'no-invalid-this': 'warn',
      'no-loop-func': 'warn',
      'no-param-reassign': 'warn',
      'no-script-url': 'warn',
      'no-useless-concat': 'warn',
      'no-void': 'warn',
      'no-warning-comments': 'warn',
      radix: 'warn',
      'require-await': 'warn',
      'init-declarations': 'warn',
      'no-shadow': 'warn',
      'no-undefined': 'warn',
      'consistent-this': 'warn',
      'func-name-matching': 'warn',
      'func-names': 'warn',
      'func-style': ['warn', 'declaration', {allowArrowFunctions: true}],
      'line-comment-position': 'warn',
      'max-depth': 'warn',
      'max-nested-callbacks': 'warn',
      'no-bitwise': 'warn',
      'no-continue': 'warn',
      'no-inline-comments': 'warn',
      'no-multi-assign': 'warn',
      'no-negated-condition': 'warn',
      'no-nested-ternary': 'warn',
      'no-plusplus': 'warn',
      'no-underscore-dangle': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-rest-params': 'warn',
    },
  },
];
