version: '3.8'
services:
  osmexport:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: osmexport
    volumes:
      - ../:/app
    ports:
      - 3000:3000
      - 9229:9229
