---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "osmexport.fullname" . }}
  labels:
    {{- include "osmexport.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    # Named `metrics` because the ServiceMonitor selects the port by this name.
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "osmexport.selectorLabels" . | nindent 4 }}
