name: Docker

on: [push, pull_request]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run tests
        run: |
          if [ -f docker/docker-compose.test.yml ]; then
            docker-compose --file docker/docker-compose.test.yml build
            docker-compose --file docker/docker-compose.test.yml run sut
          else
            docker build --file docker/Dockerfile .
          fi

  # Push image to GitHub Packages.
  push:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.pkg.github.com/atgardner/osmexport/osmexport

      - name: Build and push Docker images
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
